name: test-coverage
on:
  push:
    branches:
      - main
jobs: 
  test-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

# Set up Go environment and run tests with coverage
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.24'
      
      - name: Install dependencies
        run:
          cd backend &&
          go mod tidy
    

      - name: run unit tests with coverage
        working-directory: ./backend  
        run:
         go test -v ./...


      - name: generate coverage report
        working-directory: ./backend
        run: |
          go test -coverprofile=coverage.out .

      - name: check coverage
        working-directory: ./backend
        run: |
          go tool cover -func=coverage.out | grep total | awk '{print $3}'
          echo "total_coverage=$coverage" >> $GITHUB_OUTPUT
          echo "Coverage: $coverage"
          
      - name: Fail if coverage is below threshold
        working-directory: ./backend
        run: |
          coverage=$(go tool cover -func=coverage.out | grep total | awk '{print $3}' | sed 's/%//')
          threshold=50.0
          if (( $(echo "$coverage < $threshold" | bc -l) )); then
            echo "Code coverage $coverage% is below the threshold of $threshold%"
            exit 1
          else
            echo "Code coverage $coverage% meets the threshold of $threshold%"
          fi    
      
  build_and_push:
    runs-on: ubuntu-latest
    needs: test-coverage
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        include:
          - context: backend
            image: backend
          - context: frontend
            image: frontend
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        run: |
          OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          IMAGE_NAME=ghcr.io/$OWNER/ocp-guestbook-${{ matrix.image }}:${{ github.sha }}
          IMAGE_LATEST=ghcr.io/$OWNER/ocp-guestbook-${{ matrix.image }}:latest
          podman build -t $IMAGE_NAME -t $IMAGE_LATEST ./${{ matrix.context }}
          podman push $IMAGE_NAME 
          podman push $IMAGE_LATEST


  